
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author losel
 */
public class VentanaAgenda extends javax.swing.JFrame {

    AgendaBD agenda;
    Contacto contacto;

    /**
     * Creates new form VentanaAgenda
     */
    public VentanaAgenda() {
        initComponents();
        agenda = new AgendaBD();
        tfNom.requestFocus();
        rellenarListaDesplegable();
    }

    public void rellenarListaDesplegable() {
        ResultSet res = agenda.obtenerRegistros("Contactos");
        try {
            if (res != null) {
                chSeleccionar.removeAllItems();
                while (res.next()) {
                    chSeleccionar.addItem(res.getString("Nombre"));
                }
            }
        } catch (SQLException e) {
            System.out.println("Error rellenar lista.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chSeleccionar = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        tfDir = new javax.swing.JTextField();
        tfTlf = new javax.swing.JTextField();
        tfEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfLoc = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        bNew = new javax.swing.JButton();
        bMod = new javax.swing.JButton();
        bErase = new javax.swing.JButton();
        bOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(457, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccionar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 33, -1, -1));

        chSeleccionar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chSeleccionarItemStateChanged(evt);
            }
        });
        getContentPane().add(chSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 28, 285, -1));

        jLabel2.setText("Datos del Contacto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 85, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 159, -1, -1));

        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel6.setText("Edad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        tfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomActionPerformed(evt);
            }
        });
        getContentPane().add(tfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 270, -1));

        tfDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDirActionPerformed(evt);
            }
        });
        getContentPane().add(tfDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 270, -1));

        tfTlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTlfActionPerformed(evt);
            }
        });
        getContentPane().add(tfTlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 270, -1));

        tfEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEdadActionPerformed(evt);
            }
        });
        getContentPane().add(tfEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 270, -1));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel8.setText("Localidad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        tfLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLocActionPerformed(evt);
            }
        });
        getContentPane().add(tfLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, -1));

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 270, -1));

        bNew.setText("Nuevo");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });
        getContentPane().add(bNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 160, -1));

        bMod.setText("Modificar");
        getContentPane().add(bMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 160, -1));

        bErase.setText("Borrar");
        getContentPane().add(bErase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, -1));

        bOut.setText("Salir");
        getContentPane().add(bOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chSeleccionarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chSeleccionarItemStateChanged
        String nom = (String) chSeleccionar.getSelectedItem();
        Contacto contacto = agenda.obtenerContacto(nom);
        if (contacto != null) {
            tfNom.setText(contacto.getNombre());
            tfDir.setText(contacto.getDireccion());
            tfEmail.setText(contacto.getEmail());
            tfTlf.setText(contacto.getTelefono());
            tfEdad.setText("" + contacto.getEdad());
            tfLoc.setText(contacto.getLocalidad());
        }
        tfNom.requestFocus();
    }//GEN-LAST:event_chSeleccionarItemStateChanged

    private void tfNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomActionPerformed
        tfDir.requestFocus();
    }//GEN-LAST:event_tfNomActionPerformed

    private void tfDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDirActionPerformed
        tfLoc.requestFocus();
    }//GEN-LAST:event_tfDirActionPerformed

    private void tfLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLocActionPerformed
        tfEdad.requestFocus();
    }//GEN-LAST:event_tfLocActionPerformed

    private void tfTlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTlfActionPerformed
        tfLoc.requestFocus();
    }//GEN-LAST:event_tfTlfActionPerformed

    private void tfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEdadActionPerformed
        tfEmail.requestFocus();
    }//GEN-LAST:event_tfEdadActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        bNew.requestFocus();
    }//GEN-LAST:event_tfEmailActionPerformed

    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        String nom=tfNom.getText();
        String dir=tfDir.getText();
        String loc=tfLoc.getText();
        String email=tfEmail.getText();
        String tlf=tfTlf.getText();
        int edad=Integer.parseInt(tfEdad.getText());
        Contacto nuevoContacto=new Contacto(nom, dir, loc, tlf, email, edad);
        agenda.insertarContacto(nuevoContacto);
        rellenarListaDesplegable();
    }//GEN-LAST:event_bNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bErase;
    private javax.swing.JButton bMod;
    private javax.swing.JButton bNew;
    private javax.swing.JButton bOut;
    private javax.swing.JComboBox chSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfDir;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLoc;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfTlf;
    // End of variables declaration//GEN-END:variables
}
