
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losel
 */
public class EjercicioOpcional extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioOpcional
     */
    public EjercicioOpcional() {
        initComponents();
    }
    int cont=0;
    double sum=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAlerta = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        dbAceptar = new javax.swing.JButton();
        tfNota = new javax.swing.JTextField();
        tfContador = new javax.swing.JTextField();
        tfMedia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bInsertar = new javax.swing.JButton();
        bCalcular = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();

        dAlerta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dAlertaKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Valor incorrecto o campo vacío");

        dbAceptar.setText("Aceptar");
        dbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbAceptarActionPerformed(evt);
            }
        });
        dbAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbAceptarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dAlertaLayout = new javax.swing.GroupLayout(dAlerta.getContentPane());
        dAlerta.getContentPane().setLayout(dAlertaLayout);
        dAlertaLayout.setHorizontalGroup(
            dAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAlertaLayout.createSequentialGroup()
                .addGroup(dAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dAlertaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(dAlertaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(dbAceptar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        dAlertaLayout.setVerticalGroup(
            dAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAlertaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbAceptar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNotaActionPerformed(evt);
            }
        });

        tfContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Nota");

        jLabel2.setText("Contador");

        jLabel3.setText("Media");

        bInsertar.setText("Insertar");
        bInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });
        bInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bInsertarKeyReleased(evt);
            }
        });

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCalcular)
                    .addComponent(bInsertar)
                    .addComponent(bBorrar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNotaActionPerformed
        try{
            double auxSum=Mate.insertarNumero(Double.parseDouble(tfNota.getText()));
            sum=sum+auxSum;
            tfNota.setText(null);
            tfNota.requestFocus();
            cont++;
            tfContador.setText(""+cont);
        }catch(NumberFormatException e){
            dAlerta.pack();
            dAlerta.setVisible(true);
        }catch(RangoNumeroException e){
            dAlerta.pack();
            dAlerta.setVisible(true);
        }
    }//GEN-LAST:event_tfNotaActionPerformed

    private void tfContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContadorActionPerformed

    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarActionPerformed
        try{
            double auxSum=Mate.insertarNumero(Double.parseDouble(tfNota.getText()));
            sum=sum+auxSum;
            tfNota.setText(null);
            tfNota.requestFocus();
            cont++;
            tfContador.setText(""+cont);
        }catch(NumberFormatException e){
            dAlerta.pack();
            dAlerta.setVisible(true);
        }catch(RangoNumeroException e){
            dAlerta.pack();
            dAlerta.setVisible(true);
        }
    }//GEN-LAST:event_bInsertarActionPerformed

    private void bInsertarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bInsertarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bInsertarKeyReleased

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        tfNota.setText("");
        tfContador.setText("");
        tfMedia.setText("");
        cont=0;
        sum=0;
    }//GEN-LAST:event_bBorrarActionPerformed

    private void dbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbAceptarActionPerformed
        dAlerta.setVisible(false);
        tfNota.setText("");
    }//GEN-LAST:event_dbAceptarActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        tfMedia.setText(""+Math.round((sum/cont)*100)/100d);
    }//GEN-LAST:event_bCalcularActionPerformed

    private void dAlertaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dAlertaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dAlertaKeyReleased

    private void dbAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbAceptarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dAlerta.setVisible(false);
            tfNota.setText("");
        }
    }//GEN-LAST:event_dbAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioOpcional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton bInsertar;
    private javax.swing.JDialog dAlerta;
    private javax.swing.JButton dbAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfContador;
    private javax.swing.JTextField tfMedia;
    private javax.swing.JTextField tfNota;
    // End of variables declaration//GEN-END:variables
}
