
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losel
 */
public class VistaPartido extends javax.swing.JFrame {
    DefaultTableModel modelo;
    Controlador controlador;
    /**
     * Creates new form VistaPartido
     */
    public VistaPartido() {
        modelo=new DefaultTableModel();
        initComponents();
        controlador=new Controlador();
        rellenarJornadas();
        rellenarPartidos();
        modelo.addColumn("Tiros Libres");
        modelo.addColumn("Canastas");
        modelo.addColumn("Triples");
    }
    
    public void rellenarJornadas(){
        ResultSet resultado=controlador.obtenerRegistros("Jornadas");
        try {
            if(resultado!=null){
                while(resultado.next()){
                    cbJornada.addItem(resultado.getString("jornada"));
                }
            }
        } catch (Exception e) {
            System.out.println("Fallo al rellenar jornadas");
        }
    }
    
    public void rellenarPartidos(){
        cbPartido.removeAll();
        ResultSet resultado=controlador.obtenerRegistrosGroup("Partidos",(String) cbJornada.getSelectedItem(),"codigoPartido");
        try {
            if(resultado!=null){
                
                while(resultado.next()){
                    cbPartido.addItem(resultado.getString("codigoPartido"));
                    System.out.println(resultado.getString("codigoPartido"));
                }
            }
        } catch (Exception e) {
            System.out.println("Fallo al rellenar jornadas");
        }
    }
    
    public void rellenarDatosPartido(){
        ResultSet resultadoLocal = controlador.obtenerEquipoLocal((String) cbJornada.getSelectedItem(),(String) cbPartido.getSelectedItem());
        ResultSet resultadoVisitante=controlador.obtenerEquipoVisitante((String) cbJornada.getSelectedItem(), (String) cbPartido.getSelectedItem());
        try {
            tfFecha.setText(resultadoLocal.getString("fecha"));
            tfEL.setText(resultadoLocal.getString("nombre"));
            tfEV.setText(resultadoVisitante.getString("nombre"));
            
        } catch (SQLException e) {
            System.out.println("Fallo al rellenar los datos del partido");
        }
    }
    
    public void rellenarTablaCanastas(){
        modelo.setRowCount(0);
        
        ResultSet resultadoLocal = controlador.obtenerCanastas((String) cbJornada.getSelectedItem(), (String) cbPartido.getSelectedItem(), tfEL.getText());
        ResultSet resultadoVisitante = controlador.obtenerCanastas((String) cbJornada.getSelectedItem(), (String) cbPartido.getSelectedItem(), tfEV.getText());
        try {
            if(resultadoVisitante!=null && resultadoLocal!=null){
                float tiroLibreEL=resultadoLocal.getFloat("canastas1")/resultadoLocal.getFloat("intentos1")*100;
                float canastasEL=resultadoLocal.getFloat("canastas2")/resultadoLocal.getFloat("intentos2")*100;
                float triplesEL=resultadoLocal.getFloat("canastas3")/resultadoLocal.getFloat("intentos3")*100;
                modelo.addRow(new Object [] {(Math.round(tiroLibreEL * 100d) / 100d), 
                    (Math.round(canastasEL * 100d) / 100d),
                    (Math.round(triplesEL * 100d) / 100d)});
              
                
                float tiroLibreEV=resultadoVisitante.getFloat("canastas1")/resultadoVisitante.getFloat("intentos1")*100;
                float canastasEV=resultadoVisitante.getFloat("canastas2")/resultadoVisitante.getFloat("intentos2")*100;
                float triplesEV=resultadoVisitante.getFloat("canastas3")/resultadoVisitante.getFloat("intentos3")*100;
                modelo.addRow(new Object [] {(Math.round(tiroLibreEV * 100d) / 100d), 
                    (Math.round(canastasEV * 100d) / 100d),
                    (Math.round(triplesEV * 100d) / 100d)});
            }        
        } catch (Exception e) {
            System.out.println("Fallo a la hora de rellenar la tabla canastas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        tfEV = new javax.swing.JTextField();
        tfEL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();
        cbPartido = new java.awt.Choice();
        cbJornada = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jornada");

        jLabel2.setText("Partido");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Datos Partido");

        jLabel4.setText("Fecha");

        jLabel5.setText("Equipo Visitante");

        jLabel6.setText("Equipo Local");

        tfFecha.setEditable(false);

        tfEV.setEditable(false);

        tfEL.setEditable(false);

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Visitante");

        jLabel8.setText("Local");

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        cbPartido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPartidoItemStateChanged(evt);
            }
        });

        cbJornada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJornadaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(160, 160, 160))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEV)
                                    .addComponent(tfEL)
                                    .addComponent(tfFecha)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void cbJornadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJornadaItemStateChanged
        rellenarPartidos();
    }//GEN-LAST:event_cbJornadaItemStateChanged

    private void cbPartidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPartidoItemStateChanged
        rellenarDatosPartido();
        rellenarTablaCanastas();
    }//GEN-LAST:event_cbPartidoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalir;
    private java.awt.Choice cbJornada;
    private java.awt.Choice cbPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfEL;
    private javax.swing.JTextField tfEV;
    private javax.swing.JTextField tfFecha;
    // End of variables declaration//GEN-END:variables
}
