/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losel
 */
public class Ejercicio1 extends javax.swing.JFrame {
    private Object dialogNuevo;

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPartido = new javax.swing.JDialog();
        labelPartido = new javax.swing.JLabel();
        tfAdd = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        labelGenerador = new javax.swing.JLabel();
        listGenerado = new java.awt.List();
        listNuevas = new java.awt.List();
        botonNuevo = new javax.swing.JToggleButton();
        botonBorrar = new javax.swing.JToggleButton();
        botonVaciar = new javax.swing.JToggleButton();
        botonGenerar = new javax.swing.JToggleButton();

        labelPartido.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        labelPartido.setText("PARTIDO");

        tfAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Añadir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogPartidoLayout = new javax.swing.GroupLayout(dialogPartido.getContentPane());
        dialogPartido.getContentPane().setLayout(dialogPartidoLayout);
        dialogPartidoLayout.setHorizontalGroup(
            dialogPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPartidoLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(dialogPartidoLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(labelPartido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogPartidoLayout.setVerticalGroup(
            dialogPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPartidoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(476, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelGenerador.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        labelGenerador.setText("GENERADOR DE QUINIELAS");
        getContentPane().add(labelGenerador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 340, 70));

        listGenerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listGeneradoActionPerformed(evt);
            }
        });
        getContentPane().add(listGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, 200));
        getContentPane().add(listNuevas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 200));

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, -1));

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, -1));

        botonVaciar.setText("Vaciar");
        botonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVaciarActionPerformed(evt);
            }
        });
        getContentPane().add(botonVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, -1));

        botonGenerar.setText("Generar");
        botonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listGeneradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listGeneradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listGeneradoActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        dialogPartido.pack();
        dialogPartido.setVisible(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        listNuevas.add(tfAdd.getText());
        tfAdd.setText(null);
        tfAdd.requestFocus();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void botonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVaciarActionPerformed
        listGenerado.removeAll();
        listNuevas.removeAll();
    }//GEN-LAST:event_botonVaciarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        try{
            listNuevas.remove(listNuevas.getSelectedIndex());
        }catch(ArrayIndexOutOfBoundsException e){}
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarActionPerformed
        int i, n;
        for(i=0; i<listNuevas.getItemCount(); i++){
	n=(int)(Math.random()*10+1);
	switch (n){
            case 1:
            case 2:
            case 3:
            case 4:
            case 5: listGenerado.add(listNuevas.getItem(i)+" - 1");break;
            case 6:
            case 7:
            case 8: listGenerado.add(listNuevas.getItem(i)+" - X");break;
            case 9:
            case 10: listGenerado.add(listNuevas.getItem(i)+" - 2");break;
            }
	}
    }//GEN-LAST:event_botonGenerarActionPerformed

    private void tfAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddActionPerformed
        listNuevas.add(tfAdd.getText());
        tfAdd.setText(null);
        tfAdd.requestFocus();
    }//GEN-LAST:event_tfAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonBorrar;
    private javax.swing.JToggleButton botonGenerar;
    private javax.swing.JToggleButton botonNuevo;
    private javax.swing.JToggleButton botonVaciar;
    private javax.swing.JDialog dialogPartido;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelGenerador;
    private javax.swing.JLabel labelPartido;
    private java.awt.List listGenerado;
    private java.awt.List listNuevas;
    private javax.swing.JTextField tfAdd;
    // End of variables declaration//GEN-END:variables
}
