
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.InputMap;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losel
 */
public class EjercicioOpcional extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioOpcional
     */
    public EjercicioOpcional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAlerta = new javax.swing.JDialog();
        lAlerta = new javax.swing.JLabel();
        bContinuar = new javax.swing.JButton();
        tfEuro = new javax.swing.JTextField();
        tfDolar = new javax.swing.JTextField();
        tfLibra = new javax.swing.JTextField();
        bLimpiar = new javax.swing.JToggleButton();
        bSalir = new javax.swing.JButton();
        lEuro = new javax.swing.JLabel();
        lDolar = new javax.swing.JLabel();
        lLibra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lAlerta.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        lAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAlerta.setText("INTRODUCE UN CARACTER CORRECTO");

        bContinuar.setText("Continuar");
        bContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContinuarActionPerformed(evt);
            }
        });
        bContinuar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bContinuarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout dAlertaLayout = new javax.swing.GroupLayout(dAlerta.getContentPane());
        dAlerta.getContentPane().setLayout(dAlertaLayout);
        dAlertaLayout.setHorizontalGroup(
            dAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dAlertaLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(dAlertaLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(bContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dAlertaLayout.setVerticalGroup(
            dAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAlertaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bContinuar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfEuro.setText("0");
        tfEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEuroActionPerformed(evt);
            }
        });
        tfEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEuroKeyReleased(evt);
            }
        });

        tfDolar.setText("0");
        tfDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDolarKeyReleased(evt);
            }
        });

        tfLibra.setText("0");
        tfLibra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLibraKeyReleased(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        lEuro.setText("Euros");

        lDolar.setText("Dolares");

        lLibra.setText("Libras");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("CONVERSOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(tfDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(tfLibra, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lEuro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lDolar)
                .addGap(149, 149, 149)
                .addComponent(lLibra)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLibra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEuro)
                    .addComponent(lDolar)
                    .addComponent(lLibra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLimpiar)
                    .addComponent(bSalir))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEuroActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tfEuro.setText("");
        tfDolar.setText("");
        tfLibra.setText("");
        tfEuro.requestFocus();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void tfDolarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDolarKeyReleased
        try{
            double dolar=Double.valueOf(tfDolar.getText()).doubleValue();
            double euro=dolar*0.81;
            double libra=dolar*0.72;
            tfEuro.setText(""+Math.round(euro * 100) / 100d);
            tfLibra.setText(""+Math.round(libra * 100) / 100d);
        }catch(NumberFormatException e){
            switch(tfLibra.getText()){
                case "" :
                    tfEuro.setText("0");
                    tfDolar.setText("0");
                    tfLibra.setText("");
                    ;break;
                default:
                    dAlerta.pack();
                    dAlerta.setVisible(true);   
            } 
        }
    }//GEN-LAST:event_tfDolarKeyReleased

    private void tfLibraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLibraKeyReleased
        try{
            double libra=Double.valueOf(tfLibra.getText()).doubleValue();
            double euro=libra*1.31;
           double dolar=libra*1.39;
            tfEuro.setText(""+Math.round(euro * 100) / 100d);
            tfDolar.setText(""+Math.round(dolar * 100) / 100d);
        }catch(NumberFormatException e){
            switch(tfLibra.getText()){
                case "" :
                    tfEuro.setText("0");
                    tfDolar.setText("0");
                    tfLibra.setText("");
                    ;break;
                default:
                    dAlerta.pack();
                    dAlerta.setVisible(true);   
            } 
        } 
    }//GEN-LAST:event_tfLibraKeyReleased

    private void bContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContinuarActionPerformed
        dAlerta.setVisible(false);
    }//GEN-LAST:event_bContinuarActionPerformed

    private void bContinuarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bContinuarKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dAlerta.setVisible(false);
        }
    }//GEN-LAST:event_bContinuarKeyReleased

    private void tfEuroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEuroKeyReleased
        try{
           double euro=Double.valueOf(tfEuro.getText()).doubleValue();
           double libra=euro*0.88;
           double dolar=euro*1.23;
            tfLibra.setText(""+Math.round(libra * 100) / 100d);
            tfDolar.setText(""+Math.round(dolar * 100) / 100d);
        }catch(NumberFormatException e){
            switch(tfEuro.getText()){
                case "" :
                    tfEuro.setText("");
                    tfDolar.setText("0");
                    tfLibra.setText("0");
                    ;break;
                default:
                    dAlerta.pack();
                    dAlerta.setVisible(true);   
            }           
        }
    }//GEN-LAST:event_tfEuroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioOpcional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bContinuar;
    private javax.swing.JToggleButton bLimpiar;
    private javax.swing.JButton bSalir;
    private javax.swing.JDialog dAlerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAlerta;
    private javax.swing.JLabel lDolar;
    private javax.swing.JLabel lEuro;
    private javax.swing.JLabel lLibra;
    private javax.swing.JTextField tfDolar;
    private javax.swing.JTextField tfEuro;
    private javax.swing.JTextField tfLibra;
    // End of variables declaration//GEN-END:variables
}
