/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losel
 */
public class Ejercicio2 extends java.awt.Frame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        for(int i=1; i<=31; i++){
            choiceDia.addItem(i+"");
        }
        choiceMes.addItem("Enero");
        choiceMes.addItem("Febrero");
        choiceMes.addItem("Marzo");
        choiceMes.addItem("Abril");
        choiceMes.addItem("Mayo");
        choiceMes.addItem("Junio");
        choiceMes.addItem("Julio");
        choiceMes.addItem("Agosto");
        choiceMes.addItem("Septiembre");
        choiceMes.addItem("Octubre");
        choiceMes.addItem("Noviembre");
        choiceMes.addItem("Diciembre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableDia = new java.awt.Label();
        scrollbarYear = new java.awt.Scrollbar();
        choiceDia = new java.awt.Choice();
        labelMes = new java.awt.Label();
        choiceMes = new java.awt.Choice();
        buttonReset = new java.awt.Button();

        setMinimumSize(new java.awt.Dimension(400, 260));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lableDia.setText("Dia");
        add(lableDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        scrollbarYear.setMaximum(378);
        scrollbarYear.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scrollbarYear.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollbarYearAdjustmentValueChanged(evt);
            }
        });
        add(scrollbarYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, -1));

        choiceDia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceDiaItemStateChanged(evt);
            }
        });
        add(choiceDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, -1));

        labelMes.setText("Mes");
        add(labelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        choiceMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceMesItemStateChanged(evt);
            }
        });
        add(choiceMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 130, -1));

        buttonReset.setLabel("Resetear");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });
        add(buttonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void scrollbarYearAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrollbarYearAdjustmentValueChanged
        System.out.println(""+scrollbarYear.getValue());
        if(scrollbarYear.getValue()<=30){
            choiceDia.select(scrollbarYear.getValue());
            choiceMes.select(0);
        }else{
            if(scrollbarYear.getValue()<=58){
                choiceDia.select(scrollbarYear.getValue()-31);
                choiceMes.select(1);
            }else{
                if(scrollbarYear.getValue()<=89){
                    choiceDia.select(scrollbarYear.getValue()-59);
                    choiceMes.select(2);
                }else{
                    if(scrollbarYear.getValue()<=119){
                        choiceDia.select(scrollbarYear.getValue()-90);
                        choiceMes.select(3);
                    }else{
                        if(scrollbarYear.getValue()<=150){
                            choiceDia.select(scrollbarYear.getValue()-120);
                            choiceMes.select(4);
                        }else{
                            if(scrollbarYear.getValue()<=180){
                                choiceDia.select(scrollbarYear.getValue()-151);
                                choiceMes.select(5);
                            }else{
                                if(scrollbarYear.getValue()<=211){
                                    choiceDia.select(scrollbarYear.getValue()-181);
                                    choiceMes.select(6);
                                }else{
                                    if(scrollbarYear.getValue()<=242){
                                        choiceDia.select(scrollbarYear.getValue()-212);
                                        choiceMes.select(7);
                                    }else{
                                        if(scrollbarYear.getValue()<=272){
                                            choiceDia.select(scrollbarYear.getValue()-243);
                                            choiceMes.select(8);
                                        }else{
                                            if(scrollbarYear.getValue()<=303){
                                                choiceDia.select(scrollbarYear.getValue()-273);
                                                choiceMes.select(9);
                                            }else{
                                                if(scrollbarYear.getValue()<=333){
                                                    choiceDia.select(scrollbarYear.getValue()-304);
                                                    choiceMes.select(10);
                                                }else{
                                                    choiceDia.select(scrollbarYear.getValue()-334);
                                                    choiceMes.select(11);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        switch(choiceMes.getSelectedItem()){
            case "Enero": ;
            case "Marzo": ;
            case "Mayo": ;
            case "Julio": ;
            case "Agosto": ;
            case "Octubre": ;
            case "Diciembre":
                if(choiceDia.getItemCount()==30){
                    choiceDia.addItem(31+"");
                }
                if(choiceDia.getItemCount()==28){
                    choiceDia.addItem(29+"");
                    choiceDia.addItem(30+"");
                    choiceDia.addItem(31+"");
                }
            ; break;
            case "Abril": ;
            case "Junio": ;
            case "Septiembre": ;
            case "Noviembre": ;
                if(choiceDia.getItemCount()==31){
                    choiceDia.remove(30);
                }
                if(choiceDia.getItemCount()==28){
                    choiceDia.addItem(29+"");
                    choiceDia.addItem(30+"");
                }
            ; break;
            case "Febrero":
                if(choiceDia.getItemCount()==31){
                    choiceDia.remove(30);
                    choiceDia.remove(29);
                    choiceDia.remove(28);
                }
                if(choiceDia.getItemCount()==30){
                    choiceDia.remove(29);
                    choiceDia.remove(28);
                }
        }
    }//GEN-LAST:event_scrollbarYearAdjustmentValueChanged

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        choiceDia.select(0);
        choiceMes.select(0);
        scrollbarYear.setValue(0);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void choiceMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceMesItemStateChanged
        switch(choiceMes.getSelectedItem()){
            case "Enero": ;
            case "Marzo": ;
            case "Mayo": ;
            case "Julio": ;
            case "Agosto": ;
            case "Octubre": ;
            case "Diciembre":
                if(choiceDia.getItemCount()==30){
                    choiceDia.addItem(31+"");
                }
                if(choiceDia.getItemCount()==28){
                    choiceDia.addItem(29+"");
                    choiceDia.addItem(30+"");
                    choiceDia.addItem(31+"");
                }
            ; break;
            case "Abril": ;
            case "Junio": ;
            case "Septiembre": ;
            case "Noviembre": ;
                if(choiceDia.getItemCount()==31){
                    choiceDia.remove(30);
                }
                if(choiceDia.getItemCount()==28){
                    choiceDia.addItem(29+"");
                    choiceDia.addItem(30+"");
                }
            ; break;
            case "Febrero":
                if(choiceDia.getItemCount()==31){
                    choiceDia.remove(30);
                    choiceDia.remove(29);
                    choiceDia.remove(28);
                }
                if(choiceDia.getItemCount()==30){
                    choiceDia.remove(29);
                    choiceDia.remove(28);
                }
        }
        int sum=Integer.parseInt(choiceDia.getSelectedItem());
        if(choiceMes.getSelectedIndex()==0){
            scrollbarYear.setValue(sum);
        }else{
            if(choiceMes.getSelectedIndex()==1){
               scrollbarYear.setValue(sum+30); 
            }else{
                if(choiceMes.getSelectedIndex()==2){
                    scrollbarYear.setValue(sum+58);
                }else{
                    if(choiceMes.getSelectedIndex()==3){
                        scrollbarYear.setValue(sum+89);
                    }else{
                        if(choiceMes.getSelectedIndex()==4){
                            scrollbarYear.setValue(sum+119);
                        }else{
                            if(choiceMes.getSelectedIndex()==5){
                                scrollbarYear.setValue(sum+150);
                            }else{
                                if(choiceMes.getSelectedIndex()==6){
                                    scrollbarYear.setValue(sum+180);
                                }else{
                                    if(choiceMes.getSelectedIndex()==7){
                                        scrollbarYear.setValue(sum+211);
                                    }else{
                                        if(choiceMes.getSelectedIndex()==8){
                                            scrollbarYear.setValue(sum+242);
                                        }else{
                                            if(choiceMes.getSelectedIndex()==9){
                                                scrollbarYear.setValue(sum+272);
                                            }else{
                                                if(choiceMes.getSelectedIndex()==10){
                                                    scrollbarYear.setValue(sum+303);
                                                }else{
                                                    scrollbarYear.setValue(sum+333);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_choiceMesItemStateChanged

    private void choiceDiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceDiaItemStateChanged
        int sum=Integer.parseInt(choiceDia.getSelectedItem())-1;
        if(choiceMes.getSelectedIndex()==0){
            scrollbarYear.setValue(sum);
        }else{
            if(choiceMes.getSelectedIndex()==1){
               scrollbarYear.setValue(sum+30); 
            }else{
                if(choiceMes.getSelectedIndex()==2){
                    scrollbarYear.setValue(sum+58);
                }else{
                    if(choiceMes.getSelectedIndex()==3){
                        scrollbarYear.setValue(sum+89);
                    }else{
                        if(choiceMes.getSelectedIndex()==4){
                            scrollbarYear.setValue(sum+119);
                        }else{
                            if(choiceMes.getSelectedIndex()==5){
                                scrollbarYear.setValue(sum+150);
                            }else{
                                if(choiceMes.getSelectedIndex()==6){
                                    scrollbarYear.setValue(sum+180);
                                }else{
                                    if(choiceMes.getSelectedIndex()==7){
                                        scrollbarYear.setValue(sum+211);
                                    }else{
                                        if(choiceMes.getSelectedIndex()==8){
                                            scrollbarYear.setValue(sum+242);
                                        }else{
                                            if(choiceMes.getSelectedIndex()==9){
                                                scrollbarYear.setValue(sum+272);
                                            }else{
                                                if(choiceMes.getSelectedIndex()==10){
                                                    scrollbarYear.setValue(sum+303);
                                                }else{
                                                    scrollbarYear.setValue(sum+333);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_choiceDiaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonReset;
    private java.awt.Choice choiceDia;
    private java.awt.Choice choiceMes;
    private java.awt.Label labelMes;
    private java.awt.Label lableDia;
    private java.awt.Scrollbar scrollbarYear;
    // End of variables declaration//GEN-END:variables
}
