/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losel
 */
public class Ejercicio3 extends java.awt.Frame {

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAdd = new javax.swing.JDialog();
        lTemasDialog = new java.awt.Label();
        textFieldDialogAdd = new java.awt.TextField();
        buttonDialogAdd = new java.awt.Button();
        label2 = new java.awt.Label();
        labelOposicion = new java.awt.Label();
        textFieldOposicion = new java.awt.TextField();
        labelPreparados = new java.awt.Label();
        labelObtenidos = new java.awt.Label();
        listObtenidos = new java.awt.List();
        listPreparados = new java.awt.List();
        buttonAdd = new java.awt.Button();
        buttonNew = new java.awt.Button();
        buttonSimular = new java.awt.Button();
        buttonGenerate = new java.awt.Button();
        label1 = new java.awt.Label();
        textFieldProbabilidad = new java.awt.TextField();
        labelPercentaje = new java.awt.Label();

        dialogAdd.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTemasDialog.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lTemasDialog.setText("Temas Preparados");
        dialogAdd.getContentPane().add(lTemasDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        textFieldDialogAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDialogAddActionPerformed(evt);
            }
        });
        dialogAdd.getContentPane().add(textFieldDialogAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 20));

        buttonDialogAdd.setLabel("Añadir");
        buttonDialogAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDialogAddActionPerformed(evt);
            }
        });
        dialogAdd.getContentPane().add(buttonDialogAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        dialogAdd.getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        setMinimumSize(new java.awt.Dimension(449, 353));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelOposicion.setText("Nº Temas Oposición");
        add(labelOposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        add(textFieldOposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        labelPreparados.setText("Temas Preparados");
        add(labelPreparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        labelObtenidos.setText("Temas Obtenidos");
        add(labelObtenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        add(listObtenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, 120));
        add(listPreparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 120));

        buttonAdd.setLabel("Añadir");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        add(buttonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 60, -1));

        buttonNew.setLabel("Nuevo");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });
        add(buttonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, -1));

        buttonSimular.setLabel("Simular");
        buttonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimularActionPerformed(evt);
            }
        });
        add(buttonSimular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, -1));

        buttonGenerate.setLabel("Generar");
        buttonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateActionPerformed(evt);
            }
        });
        add(buttonGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        label1.setText("Probabilidad");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));
        add(textFieldProbabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 110, -1));

        labelPercentaje.setText("%");
        add(labelPercentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 300, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        dialogAdd.pack();
        dialogAdd.setVisible(true);
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDialogAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDialogAddActionPerformed
        listPreparados.add(textFieldDialogAdd.getText());
        textFieldDialogAdd.setText(null);
        textFieldDialogAdd.requestFocus();
    }//GEN-LAST:event_buttonDialogAddActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        listObtenidos.removeAll();
        listPreparados.removeAll();
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimularActionPerformed
        int numTemas=Integer.parseInt(textFieldOposicion.getText());
        if(listPreparados.getItemCount()>2){
            for(int i=0; i<=2; i++){
                listObtenidos.add(""+(int)(Math.random()*numTemas+1));
            }
        }
    }//GEN-LAST:event_buttonSimularActionPerformed

    private void buttonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateActionPerformed
        int numTemas=Integer.parseInt(textFieldOposicion.getText());
        System.out.println(""+numTemas);
        double numPreparados=listPreparados.getItemCount();
        System.out.println(""+numPreparados);
        double division=numPreparados/numTemas;
        System.out.println(""+division);
        double probabilidad=division*100;
        textFieldProbabilidad.setText(""+probabilidad);
    }//GEN-LAST:event_buttonGenerateActionPerformed

    private void textFieldDialogAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDialogAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDialogAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonAdd;
    private java.awt.Button buttonDialogAdd;
    private java.awt.Button buttonGenerate;
    private java.awt.Button buttonNew;
    private java.awt.Button buttonSimular;
    private javax.swing.JDialog dialogAdd;
    private java.awt.Label lTemasDialog;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label labelObtenidos;
    private java.awt.Label labelOposicion;
    private java.awt.Label labelPercentaje;
    private java.awt.Label labelPreparados;
    private java.awt.List listObtenidos;
    private java.awt.List listPreparados;
    private java.awt.TextField textFieldDialogAdd;
    private java.awt.TextField textFieldOposicion;
    private java.awt.TextField textFieldProbabilidad;
    // End of variables declaration//GEN-END:variables
}
